---
- name: copy certificates
  copy:
    src: "../ssl/{{ item }}"
    dest: "/home/{{ ansible_user }}/ssl/{{ item }}"
  loop:
    - "ca.crt"
    - "ca.key"
    - "kube-controller-manager.crt"
    - "kube-controller-manager.key"
    - "service-accounts.key"
  become: yes

- name: check if binary already exists
  ansible.builtin.stat:
    path: "{{ kube_controller_manager_binary_local_path }}/{{ kube_controller_manager_binary_name }}"
  register: file_status

- name: copy kube-controller-manager binary
  get_url:
    url: "{{ kube_controller_manager_binary_remote_path }}"
    dest: "{{ kube_controller_manager_binary_local_path }}"
    force: no
  become: yes
  when: not file_status.stat.exists

- name: change permissions
  file:
    dest: "{{ kube_controller_manager_binary_local_path }}/{{ kube_controller_manager_binary_name }}"
    mode: a+x
  become: yes

- name: generate kubeconfig
  template:
    src: kube-controller-manager.kubeconfig.j2
    dest: /home/{{ ansible_user }}/kube-controller-manager.kubeconfig

- name: create systemd unit
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  become: yes
  notify:
    - restart kube-controller-manager

- name: enable systemd unit
  systemd_service:
    name: kube-controller-manager
    enabled: true
  become: yes
