---
- name: check if binary already exists
  ansible.builtin.stat:
    path: "{{ etcd_binary_local_path }}/{{ etcd_binary_name }}"
  register: binary_file_status

- name: copy etcd binary
  ansible.builtin.unarchive:
    src: "{{ etcd_binary_remote_pathz }}"
    dest: "{{ etcd_binary_local_path }}"
    remote_src: yes
  become: yes
  when: not binary_file_status.stat.exists

- name: change permissions
  file:
    dest: "{{ etcd_binary_local_path }}/{{ etcd_binary_name }}"
    mode: a+x
  become: yes

- name: create systemd unit
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  become: yes
  notify:
    - restart etcd

- name: enable systemd unit
  systemd_service:
    name: etcd
    enabled: true
  become: yes
