---
- name: copy certificates
  copy:
    src: "../ssl/{{ item }}"
    dest: "/home/{{ ansible_user }}/ssl/{{ item }}"
  loop:
    - "ca.crt"
    - "etcd-server.crt"
    - "etcd-server.key"
    - "etcd-{{ inventory_hostname }}.crt"
    - "etcd-{{ inventory_hostname }}.key"
  become: yes

- name: check if binary already exists
  ansible.builtin.stat:
    path: "{{ etcd_binary_local_path }}/{{ etcd_binary_name }}"
  register: binary_file_status

- name: unpack etcd binary
  ansible.builtin.unarchive:
    src: "{{ etcd_binary_remote_pathz }}"
    dest: /tmp
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  become: yes
  when: not binary_file_status.stat.exists

- name: copy etcd binary
  copy:
    src: "/tmp/{{ item }}"
    dest: "{{ etcd_binary_local_path }}/{{ item }}"
    remote_src: yes
  loop:
    - "etcd"
    - "etcdctl"
    - "etcdutl"
  become: yes
  when: not binary_file_status.stat.exists

- name: change permissions
  file:
    dest: "{{ etcd_binary_local_path }}/{{ etcd_binary_name }}"
    mode: a+x
  become: yes

- name: create systemd unit
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  become: yes
  notify:
    - restart etcd

- name: enable systemd unit
  systemd_service:
    name: etcd
    enabled: true
  become: yes
