controllers:
  hosts:
    controller-0:
      ansible_host: 192.168.50.200
    controller-1:
      ansible_host: 192.168.50.201
    controller-2:
      ansible_host: 192.168.50.202

workers:
  hosts:
    worker-0:
      ansible_host: 192.168.50.210
    worker-1:
      ansible_host: 192.168.50.211
    worker-2:
      ansible_host: 192.168.50.212

kubernetes:
  children:
    controllers:
    workers:
